appName = "chat_room"

[mysql]
host = "localhost"
name = "chatapp"
password = "Tiffany0207!"
port = 3306
tablePrefix = ""
user = "tiffany"

[log]
level = "debug"
path = "logs/chat.log"

[staticPath]
filePath = "web/static/file/"

[msgChannelType]
channelType = "gochannel"

kafkaHosts = "kafka:9092"
kafkaTopic = "go-chat-message"